project_id = "ulktsjpzckjolonlocqg"

[functions.transcribe]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.process-recurring-tasks]
verify_jwt = false

[functions.daily-reminder]
verify_jwt = false

[functions.process-ramble]
verify_jwt = false
